import { GoogleGenAI } from "@google/genai";
import { decideActionByRules, MAX_RETRIES } from "./recoveryEngine.js";

const ALLOWED_ACTIONS = new Set([
  "retry",
  "sms",
  "priority_sms",
  "stop",
  "review",
]);

// Cost control belongs at the call-site (one budget per "Start Recovery" run).
// A separate runtime flag below stops repeated Gemini requests after the API
// has explicitly reported quota/rate-limit exhaustion.
let geminiQuotaUnavailable = false;

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

/**
 * AI payment recovery decision engine.
 *
 * Gemini analyzes the payment context and recommends
 * one recovery action.
 *
 * The deterministic rule engine is used as a safety
 * fallback whenever Gemini is unavailable or invalid.
 */
export async function getAIDecision(payment, customer) {
  const model =
    process.env.GEMINI_MODEL || "gemini-2.5-flash";

  // If Gemini has already told this server that the project quota/rate limit
  // is exhausted, do not hammer the API again for every payment in the same run.
  if (geminiQuotaUnavailable) {
    return createFallbackDecision(payment, "Gemini quota/rate limit already reached");
  }

  try {
    if (!process.env.GEMINI_API_KEY) {
      throw new Error(
        "GEMINI_API_KEY is not configured"
      );
    }

    console.log(
      "[aiService] Gemini request"
    );

    // -------------------------------------------------------
    // GEMINI REQUEST
    // -------------------------------------------------------

    // Keep the request compatible with the configured Gemini model.
    // Some model/config combinations reject thinkingConfig with a generic
    // INVALID_ARGUMENT (400), which previously caused an unnecessary second
    // Gemini request for every payment. Structured JSON is still enforced by
    // responseMimeType + responseSchema.
    const config = {
      temperature: 0,
      maxOutputTokens: 800,
      responseMimeType: "application/json",
      responseSchema: {
        type: "object",
        properties: {
          action: { type: "string", enum: ["retry", "sms", "priority_sms", "stop", "review"] },
          reasoning: { type: "string" },
        },
        required: ["action", "reasoning"],
      },
    };

    let response;
    try {
      response = await ai.models.generateContent({
        model,
        contents: buildPrompt(payment, customer),
        config,
      });
    } catch (err) {
      // A quota/rate-limit response is terminal for this server process.
      // Do not retry it for the next payment.
      if (isQuotaOrRateLimitError(err)) {
        geminiQuotaUnavailable = true;
      }
      throw err;
    }

    console.log(
      "[aiService] Gemini response received"
    );

    const text = response.text?.trim();

    console.log(
      "[aiService] Gemini raw:",
      text
    );

    if (!text) {
      throw new Error(
        "Gemini returned an empty response"
      );
    }

    // -------------------------------------------------------
    // PARSE RESPONSE
    // -------------------------------------------------------

    let parsed;

    try {
      parsed = JSON.parse(text);
    } catch {
      // Safety fallback in case Gemini adds
      // extra text around the JSON object.
      const start = text.indexOf("{");
      const end = text.lastIndexOf("}");

      if (start === -1 || end === -1) {
        throw new Error(
          `Gemini returned no JSON object: ${text}`
        );
      }

      const jsonText = text.slice(
        start,
        end + 1
      );

      parsed = JSON.parse(jsonText);
    }

    // -------------------------------------------------------
    // VALIDATE ACTION
    // -------------------------------------------------------

    if (!ALLOWED_ACTIONS.has(parsed.action)) {
      throw new Error(
        `Gemini returned unsupported action: ${parsed.action}`
      );
    }

    // -------------------------------------------------------
    // SAFETY: RETRY LIMIT
    // -------------------------------------------------------

    if (
      parsed.action === "retry" &&
      payment.retryCount >= MAX_RETRIES
    ) {
      console.warn(
        "[aiService] Gemini suggested retry after " +
          "the retry limit. Using rules instead."
      );

      return createFallbackDecision(
        payment,
        "Gemini recommendation violated retry limit"
      );
    }

    // -------------------------------------------------------
    // SUCCESS
    // -------------------------------------------------------

    return {
      recommendedAction: parsed.action,

      reasoning:
        parsed.reasoning?.trim() ||
        "Gemini selected this recovery action based on the payment context.",

      /*
       * SMS text is intentionally generated by the
       * application's SMS service rather than Gemini.
       */
      smsMessage: null,

      model,

      rawResponse: text,
    };
  } catch (err) {
    console.error(
      "[aiService] Gemini call failed, falling back to rules:",
      err.message
    );

    return createFallbackDecision(
      payment,
      "Gemini unavailable"
    );
  }
}

function isQuotaOrRateLimitError(err) {
  const status = Number(err?.status || err?.statusCode || err?.code);
  const message = String(err?.message || "").toLowerCase();
  return (
    status === 429 ||
    message.includes("429") ||
    message.includes("quota") ||
    message.includes("rate limit") ||
    message.includes("resource exhausted") ||
    message.includes("too many requests")
  );
}


/**
 * Deterministic fallback.
 *
 * This guarantees that the recovery system continues
 * working even if Gemini is unavailable.
 */
function createFallbackDecision(
  payment,
  reason
) {
  const fallback =
    decideActionByRules(payment);

  return {
    recommendedAction: fallback.action,

    reasoning:
      `[fallback — ${reason}] ${fallback.reason}`,

    smsMessage: null,

    model: "rules-fallback",

    rawResponse: null,
  };
}

/**
 * Prompt sent to Gemini.
 *
 * JSON formatting is handled by responseSchema,
 * so the prompt only contains the actual business
 * decision logic.
 */
function buildPrompt(payment, customer) {
  return `
Analyze this failed payment and choose the best recovery action.

Customer:
Name: ${customer.name}
Previous successful payments: ${customer.successfulPaymentsCount}

Payment:
Amount: ₹${(payment.amount / 100).toFixed(2)}
Failure reason: ${payment.failureReason}
Retry count: ${payment.retryCount}

Choose exactly one action:

retry
sms
priority_sms
stop
review

Decision rules:

- Never choose retry if retry count is 2 or more.
- Choose retry for temporary failures where another attempt is reasonable.
- Choose sms for normal customer recovery.
- Choose priority_sms for urgent or high-value recovery.
- Choose stop when recovery is unlikely to succeed.
- Choose review when merchant intervention is appropriate.

Write "reasoning" for a non-technical merchant reading a dashboard, not a developer.
Requirements:
- One or two short sentences, plain English, no jargon.
- Name the specific failure reason and amount, and explain in concrete terms why
  that makes this action the right call (e.g. "This card was declined by the
  bank, not by us, so retrying the same card is unlikely to work — sending an
  SMS lets the customer choose a different payment method instead").
- Do not just restate the action name (e.g. never write "recommends SMS because
  SMS is appropriate").
- If retry count or customer payment history influenced the decision, mention it.
`;
}